/**
 * Glossary & learning content.
 *
 * Organized by category because A-Z only helps when you already know
 * the term you're looking up — which defeats the point for beginners.
 */

export type GlossaryEntry = {
  term: string;
  aliases?: string[];
  definition: string;
  practical?: string;
  caveat?: string;
};

export type GlossarySection = {
  id: string;
  title: string;
  intro?: string;
  entries: GlossaryEntry[];
};

export type Guide = {
  id: string;
  title: string;
  body: string;
};

// ---------------------------------------------------------------------------
// Workflow guides — how to use the app
// ---------------------------------------------------------------------------

export const GUIDES: Guide[] = [
  {
    id: "reading-briefing",
    title: "How to read your briefing",
    body: `
The morning briefing is generated by the AI on demand. It's built fresh each time — no caching — so the prices and news are whatever the database had when you clicked Generate.

**Market Summary** is the AI's overall take across everything you track. It's the least useful section for decisions and the most useful for getting oriented — a sentence or two about what's moving and why.

**Per-Ticker Highlights** goes through each watchlist ticker with a short paragraph covering recent price action, news catalysts, and anything notable about volume or momentum. This is where most of the briefing's value lives. If the AI mentions something specific — "AMD is up 8% on a channel-check note from Morgan Stanley" — you can trust that the news item exists because the AI pulled it from the database. It can still misinterpret what news *means*, but it can't fabricate the news itself.

**Open Positions Check** only appears if you have open trades in your journal. It flags things specific to your actual holdings — a stop level crossed, a target approached, a thesis that looks validated or broken. This is the section that makes the app feel like it's actually tracking you rather than just observing the market.

**Worth a Closer Look** is 1–3 setups the AI thinks deserve your attention today. Every entry should include what would invalidate the view — if it doesn't, the AI got lazy and you should push back. "What would change your mind?" is always a fair follow-up question in chat.

**Questions to Consider** is 2–3 educational or situation-specific prompts. These are good journal fodder — answering one of them in writing will teach you more than re-reading the briefing three times.

A briefing is not a trading signal. It's a briefing — a structured summary of what happened and what's worth thinking about. The decision is yours.
    `.trim(),
  },
  {
    id: "reading-drawer",
    title: "How to read the ticker detail drawer",
    body: `
Clicking any ticker opens the detail drawer. Here's what each section is actually showing you.

**Header** shows ticker, company name, sector, and the current price with its change over the selected timeframe. The percentage is relative to the start of the timeframe, not a daily change. "1M +4.2%" means the price is 4.2% higher than it was one month ago.

**Price chart** is daily candlesticks. Green when the close is above the open, red when below. The wicks are the high/low; the body is the open-to-close range. Volume bars are below. Timeframe buttons (1M / 3M / 6M / 1Y / 5Y) switch the window; the chart will auto-backfill more history if it doesn't have enough stored.

**Technicals panel** computes moving averages, RSI, and volume ratio from the stored bars. These are lagging indicators — they describe what has already happened, not what will. Useful for context, dangerous if used as signals in isolation.

**News** is sorted newest-first, with a relevance filter at the top. Filter to "Primary subject only" (relevance 3) when you want just the articles genuinely about this company; drop the filter when you're researching broadly.

The drawer also has external links to Yahoo Finance and CNBC in the header — use those for anything the app doesn't cover (analyst estimates, options chains, detailed financials).
    `.trim(),
  },
  {
    id: "good-journal-entry",
    title: "How to write a good journal entry",
    body: `
The journal is where most of the long-term value of this app comes from. Not because it tracks P&L — your broker does that — but because it forces you to write down *why* you made a trade before you made it, and then lets you evaluate yourself later against what you actually said at the time.

A good entry has:

**A thesis in one or two sentences.** Not "I like this stock." That's not a thesis, that's a feeling. Better: "AMD should benefit from AI datacenter capex through 2026; MI300 ramp and MI350 announcement in H2 are catalysts." Specific, dated, falsifiable.

**A stop loss.** The price at which you were wrong. If you can't think of a price that would prove the thesis wrong, you don't have a thesis, you have hope. Set it before you buy, not after the position is underwater.

**A target price, or at least a target condition.** "Sell when the gap to the 200-day SMA closes" is a valid target. "Sell at $250" is a valid target. "Sell when I feel like it" is not.

**Cost basis captured accurately.** If you know the exact fill price, use "known" mode. If you're backfilling an existing position and only remember "I spent about \$3,200 on 18 shares," use "cost basis" mode — the app tags the entry as approximate so the AI treats it accordingly.

**Notes as you go.** When something changes — new earnings, new news, you decide to add — add a short note with the date. Future-you will want to know what you were thinking in real time, not just what you remember in hindsight.

Don't skip writing a journal entry because the trade is "just a quick flip." Especially not then. Quick flips are where undisciplined thinking lives.
    `.trim(),
  },
];

// ---------------------------------------------------------------------------
// Glossary by category
// ---------------------------------------------------------------------------

export const SECTIONS: GlossarySection[] = [
  {
    id: "trading-styles",
    title: "Trading styles",
    intro: "How you approach the market — time horizon, position size, and frequency — matters more than most beginners realize. A strategy that works beautifully for one style fails completely at another.",
    entries: [
      {
        term: "Day trading",
        definition: "Opening and closing positions within the same trading day. No overnight holds.",
        practical: "Requires fast execution, constant attention, and real-time data. Not what this app is built for.",
        caveat: "Statistically, most retail day traders lose money. The edge required to beat the spread, commission drag, and your own emotions is real and rare.",
      },
      {
        term: "Swing trading",
        definition: "Holding positions from a few days to a few weeks, trying to capture medium-term price moves.",
        practical: "The sweet spot for someone who can check in daily but can't watch charts all day. Technicals (chart patterns, moving averages) matter more here than in position trading.",
        caveat: "The trap is constantly jumping between setups. Discipline on stop-losses is what separates profitable swing traders from the rest.",
      },
      {
        term: "Position trading",
        definition: "Holding for weeks to months based on fundamental thesis. The middle ground between swing and investing.",
        practical: "Position trades should always have a written thesis and a stop. The thesis is what you're right about; the stop is where you admit you were wrong.",
      },
      {
        term: "Investing",
        definition: "Holding for years, with decisions driven by fundamentals, valuation, and long-term thematic conviction.",
        practical: "Most 'trading' advice doesn't apply. Investors tolerate 30% drawdowns that would blow up a swing trader. The time horizon makes volatility noise, not signal.",
      },
      {
        term: "Income trading",
        definition: "Generating regular cash flow from positions, typically via dividends, covered calls, or cash-secured puts.",
        practical: "Conservative income strategies (covered calls on stocks you'd own anyway) can add 5–15% annualized yield to a long portfolio. Aggressive ones (short puts on volatile names) can blow up spectacularly.",
        caveat: "'Yield' is not 'free money.' Every income strategy is a trade of upside capped for downside retained.",
      },
    ],
  },

  {
    id: "reading-charts",
    title: "Reading price charts",
    intro: "The chart in the ticker drawer is a daily candlestick chart. Here's what you're actually looking at.",
    entries: [
      {
        term: "OHLC",
        aliases: ["Open", "High", "Low", "Close"],
        definition: "The four price points that define each trading day: where the stock opened, its highest and lowest trades, and where it closed.",
        practical: "Closing price is the one number most traders care about — it's where the day settled after all participants had their say. Daily returns are closing-price-to-closing-price.",
      },
      {
        term: "Candlestick",
        definition: "A visual representation of OHLC for a single period. The body spans open-to-close; the thin wicks extend to the high and low.",
        practical: "Green (or hollow) body: close is above open. Red (or filled) body: close is below open. Long wicks with small bodies often indicate indecision or rejection at a level.",
      },
      {
        term: "Gap",
        definition: "A price jump between one day's close and the next day's open, creating a visible gap in the chart with no trading in between.",
        practical: "Gaps usually happen on news released when the market was closed — earnings, a merger announcement, macro data. A gap up that immediately fills (price drops back into the gap) is often a bearish reversal signal; a gap that holds is often bullish continuation.",
      },
      {
        term: "Volume",
        definition: "The total number of shares traded in a period.",
        practical: "Volume confirms conviction. A 5% move on 3x average volume is a very different event from a 5% move on half average volume. The first suggests real buying interest; the second suggests a quiet drift.",
      },
      {
        term: "Support and resistance",
        definition: "Price levels where buying pressure (support) has historically halted declines, or selling pressure (resistance) has halted advances.",
        practical: "These levels are most useful when they've been tested multiple times. A level that's held three times is meaningful; a level someone drew on a chart once is not.",
        caveat: "When broken, support often becomes resistance and vice versa. 'Former support, now resistance' is a real phenomenon worth watching after a breakdown.",
      },
      {
        term: "Breakout",
        definition: "Price moving decisively through a resistance level (or support, in a breakdown) on expanding volume.",
        practical: "True breakouts hold and extend. False breakouts reverse quickly, often trapping late buyers. Volume is the single best filter — low-volume breakouts fail more often than they succeed.",
      },
    ],
  },

  {
    id: "technicals",
    title: "Technical indicators",
    intro: "These are math transforms applied to price and volume data. They don't predict the future. They describe the past in a way that sometimes highlights useful patterns.",
    entries: [
      {
        term: "SMA",
        aliases: ["Simple Moving Average"],
        definition: "The average closing price over N days. SMA(20) is the average of the last 20 closes.",
        practical: "Price above a rising SMA is a common definition of 'uptrend.' Price crossing below a long-term SMA (50 or 200) is a common definition of 'trouble.' These are heuristics, not rules.",
        caveat: "Moving averages lag by design. They tell you about the recent past, cleanly. They don't tell you about the future.",
      },
      {
        term: "EMA",
        aliases: ["Exponential Moving Average"],
        definition: "A weighted moving average that puts more weight on recent data. Reacts faster than SMA.",
        practical: "Short-term traders often prefer EMA because it turns faster. Longer-term traders often prefer SMA because it's stabler.",
      },
      {
        term: "RSI",
        aliases: ["Relative Strength Index"],
        definition: "A momentum oscillator that ranges from 0 to 100, measuring the speed and magnitude of recent price changes.",
        practical: "Conventional wisdom: RSI above 70 is 'overbought,' below 30 is 'oversold.' In a strong trend these thresholds get crossed and stay crossed for a long time — they stop being useful signals.",
        caveat: "RSI works well in range-bound markets and poorly in trending ones. Know which regime you're in before you trust the reading.",
      },
      {
        term: "Divergence",
        definition: "When price makes a new high (or low) but an indicator like RSI does not — or vice versa.",
        practical: "Bearish divergence: price makes a higher high, RSI makes a lower high — suggests momentum is fading. Bullish divergence: price makes a lower low, RSI makes a higher low — suggests selling is exhausting.",
        caveat: "Divergences can persist for weeks before price reacts, and many divergences never resolve the way the pattern predicts. Useful as one input among many, dangerous as a standalone signal.",
      },
      {
        term: "Volume vs. average",
        definition: "Current or recent volume expressed as a percentage of the 20-day or 50-day average.",
        practical: "200%+ of average is a meaningful move. 50% of average suggests apathy. The technicals panel in the drawer shows this as 'volume_vs_avg_pct.'",
      },
      {
        term: "Moving average crossover",
        definition: "When one moving average crosses another — e.g., 50-day SMA crossing above 200-day SMA (a 'golden cross') or below it (a 'death cross').",
        practical: "These are famous but not magical. They confirm trends that are already well underway rather than catching turns early. By the time a golden cross forms, the bottom was usually weeks or months ago.",
      },
    ],
  },

  {
    id: "news-catalysts",
    title: "News and catalysts",
    entries: [
      {
        term: "Catalyst",
        definition: "An event expected to move a stock's price — earnings, FDA decisions, product launches, macro data, analyst upgrades.",
        practical: "Knowing the catalyst calendar for your holdings (next earnings date, next expected Fed meeting, etc.) is basic hygiene. Surprise is usually bad; even good news you weren't expecting can be unsettling if your position size is wrong.",
      },
      {
        term: "Headwind / Tailwind",
        definition: "Macroeconomic or industry-level forces working against (headwind) or for (tailwind) a company.",
        practical: "Examples of tailwinds: falling interest rates for capital-heavy businesses; rising AI capex for semiconductors. Examples of headwinds: rising input costs for consumer goods; FX strength for exporters. Good commentary names the tailwinds and headwinds specifically.",
      },
      {
        term: "Earnings",
        aliases: ["EPS report", "Quarterly results"],
        definition: "Public companies report financial results every three months. The report includes revenue, profit, margin, guidance for the next quarter, and usually a conference call where management takes analyst questions.",
        practical: "Stocks move more on guidance (forward-looking commentary) than on the quarter itself. Beating the quarter but lowering guidance is often punished harder than missing the quarter but raising guidance.",
      },
      {
        term: "Guidance",
        definition: "Management's forecast for the next quarter or fiscal year, usually a range for revenue and EPS.",
        practical: "Companies manage guidance conservatively — 'under-promise and over-deliver' is the norm. A company that raises guidance twice in a row is signaling real confidence; a company that lowers guidance twice is signaling real trouble.",
      },
      {
        term: "Analyst rating",
        definition: "Wall Street analysts assign ratings (Buy/Hold/Sell or equivalents) and price targets to stocks they cover.",
        practical: "Individual analyst calls can move stocks short-term but don't drive long-term returns. The consensus (average of all analysts) is more stable and more useful — dramatic changes in consensus are more meaningful than one firm's call.",
        caveat: "Analysts tend to be herders. Most ratings cluster around Buy/Hold for companies that are performing, and dramatic downgrades often come after the stock has already fallen.",
      },
      {
        term: "Macro",
        definition: "Economy-wide factors: interest rates, inflation, GDP growth, employment, central bank policy.",
        practical: "Macro drives sectors more than individual stocks. Rate cuts tend to help growth and housing; rate hikes tend to help financials and hurt bonds. A single stock's fate inside a sector depends on its specifics, but the tide matters.",
      },
    ],
  },

  {
    id: "portfolio",
    title: "Portfolio and risk",
    entries: [
      {
        term: "Position size",
        definition: "The dollar amount (or percentage of portfolio) allocated to a single holding.",
        practical: "A common beginner mistake: position size driven by conviction feelings rather than risk calculation. A 15% position that drops 40% costs you 6% of your portfolio. A 5% position that drops 40% costs you 2%.",
      },
      {
        term: "Risk per trade",
        definition: "The amount of money you'd lose if your stop loss got hit. Not the position size — the potential loss.",
        practical: "A common framework: risk no more than 1–2% of your portfolio on any single trade. This lets you be wrong many times in a row without losing the ability to keep trading.",
      },
      {
        term: "Diversification",
        definition: "Spreading capital across positions whose returns don't all move together, so bad outcomes in one don't ruin the whole portfolio.",
        practical: "True diversification isn't just 'own more stocks.' It's owning stocks (or asset classes) with genuinely different return drivers. Four semiconductor names is not a diversified position in semis — it's one concentrated bet with four tickers on it.",
        caveat: "Correlation rises during crises. Assets that looked diversified in normal markets often drop together during panics.",
      },
      {
        term: "Concentration",
        definition: "The opposite of diversification — heavy weight in a small number of positions or themes.",
        practical: "Concentration is how most large fortunes are made and lost. It amplifies both outcomes. Knowing whether you're concentrated on purpose or by accident is more important than the level of concentration itself.",
      },
      {
        term: "Correlation",
        definition: "The degree to which two assets move together. Ranges from +1 (perfect move-together) to −1 (perfect inverse) with 0 being independent.",
        practical: "Most US stocks have correlation around 0.5–0.7 with the S&P 500. That means even a 'diversified' portfolio of 20 US large-caps will still mostly move with the market.",
      },
      {
        term: "Cost basis",
        definition: "The total amount you paid for a position, including commissions. Divided by shares owned, it's your average purchase price.",
        practical: "Cost basis matters for P&L calculations and for tax reporting. It does not matter for decision-making — a stock doesn't know what you paid for it, and your stop loss should be based on where the thesis is broken, not on your breakeven point.",
      },
      {
        term: "Unrealized vs. realized P&L",
        definition: "Unrealized: the paper gain or loss on a position you still own. Realized: the gain or loss locked in after you sell.",
        practical: "Unrealized gains aren't real until they're realized. Many traders watch a 40% gain become a 10% gain become a loss, because selling meant admitting the run was over.",
      },
    ],
  },

  {
    id: "orders",
    title: "Order types",
    intro: "This app doesn't execute trades — that happens in your broker. But the app surfaces price levels and signals that translate directly into orders.",
    entries: [
      {
        term: "Market order",
        definition: "An order to buy or sell immediately at the best available current price.",
        practical: "Fast and certain to fill. Dangerous in illiquid stocks or during volatile moments — you can pay much worse than the last-printed price if the order book is thin.",
      },
      {
        term: "Limit order",
        definition: "An order to buy at no more than, or sell at no less than, a specified price.",
        practical: "Safer than market orders for price control. The tradeoff: your order may never fill if the price doesn't reach your limit.",
      },
      {
        term: "Stop order",
        aliases: ["Stop loss"],
        definition: "An order that becomes a market order once a trigger price is touched. For a long position, a stop sits below the current price as a 'sell if it falls to X' protection.",
        practical: "The basic tool for enforcing discipline. Set it when you open the position. Do not move it further away when the trade goes against you — that's exactly how small losses become catastrophic ones.",
      },
      {
        term: "Stop-limit order",
        definition: "A stop order that triggers a limit order rather than a market order. You specify both the trigger price and the worst price you'll accept.",
        practical: "Useful when you want stop-like protection but won't accept arbitrarily bad fills. The risk: in a fast drop, price can blow through your limit without filling you, and you're left holding a losing position that just got much worse.",
      },
      {
        term: "Trailing stop",
        definition: "A stop that automatically moves up (for long positions) as the price rises, maintaining a fixed distance below the current price.",
        practical: "Lets profits run while locking in gains. Works well in strong trends, gives up too easily in choppy markets where normal volatility will take you out.",
      },
    ],
  },

  {
    id: "market-mechanics",
    title: "Market mechanics",
    entries: [
      {
        term: "Liquidity",
        definition: "How easily an asset can be bought or sold without moving its price.",
        practical: "High liquidity (AAPL, SPY): you can transact millions of dollars with barely any price impact. Low liquidity (a small-cap under $500M market cap, or the 10th-month-out option chain): even small orders can move the price 1–5%.",
        caveat: "Liquidity evaporates in crises — the worst possible time. Positions that looked liquid during normal markets become hard to exit when everyone wants out.",
      },
      {
        term: "Bid / Ask / Spread",
        definition: "Bid: highest price a buyer will pay. Ask: lowest price a seller will accept. Spread: the gap between them.",
        practical: "Liquid stocks have spreads of a cent or less. Illiquid names might have spreads of 1–3% of the share price, which is effectively a tax on trading.",
      },
      {
        term: "Market cap",
        definition: "Share price × total shares outstanding. The total market value of the company's equity.",
        practical: "Shorthand classification: large-cap (>$10B), mid-cap ($2–10B), small-cap ($300M–$2B), micro-cap (below). Rules of thumb about volatility, liquidity, and analyst coverage break down as you go smaller.",
      },
      {
        term: "Float",
        definition: "The number of shares actually available for public trading, excluding locked-up insider or institutional holdings.",
        practical: "Low-float stocks can move violently on modest news — there simply aren't enough shares to absorb buying or selling pressure smoothly.",
      },
      {
        term: "Short interest",
        definition: "The percentage of a stock's float that has been sold short and not yet covered.",
        practical: "High short interest (20%+) creates the conditions for a short squeeze — if the stock rises, shorts are forced to buy to cover, which pushes it higher, which forces more covering. Dangerous and hard to predict.",
      },
      {
        term: "Sector",
        definition: "A broad classification of companies by the business they're in. Common sectors: Technology, Financials, Healthcare, Energy, Consumer Discretionary, Consumer Staples, Industrials, Utilities, Materials, Real Estate, Communication Services.",
        practical: "Sector rotation — capital moving between sectors as macro conditions shift — is a real phenomenon. Cyclical sectors (financials, industrials) tend to lead in early recoveries; defensive sectors (utilities, staples) tend to hold up in downturns.",
      },
    ],
  },

  {
    id: "fundamentals",
    title: "Financial metrics",
    intro: "The numbers you'll see in analyst commentary and company reports. This app doesn't currently show most of these — use Yahoo Finance or your broker for deep fundamental data — but you'll encounter them constantly.",
    entries: [
      {
        term: "P/E ratio",
        aliases: ["Price-to-Earnings"],
        definition: "Current share price divided by earnings per share over the last 12 months. A measure of how richly a stock is valued relative to its profits.",
        practical: "Historical average for the S&P 500 is around 16–18. A P/E of 30 means the stock is priced for significant earnings growth; a P/E of 8 means the market expects profits to shrink. Neither is automatically 'good' or 'bad.'",
      },
      {
        term: "Forward P/E",
        definition: "P/E using projected earnings for the next 12 months rather than the last 12.",
        practical: "More useful than trailing P/E for growth companies, where the past vastly understates the likely future. Only as trustworthy as the forecast behind it.",
      },
      {
        term: "Revenue growth",
        definition: "Year-over-year change in total sales.",
        practical: "The cleanest high-level indicator of whether a business is expanding. Accelerating revenue growth in a large company is genuinely rare and usually signals something important.",
      },
      {
        term: "Gross margin",
        definition: "(Revenue − cost of goods sold) ÷ Revenue. The percentage of each dollar of sales that's left after direct costs.",
        practical: "High gross margin (70%+) is characteristic of software and luxury brands; low gross margin (5–15%) is characteristic of retail and energy. Margin trend matters more than absolute level — a company going from 40% to 55% is telling a much better story than one going from 60% to 50%.",
      },
      {
        term: "Free cash flow",
        aliases: ["FCF"],
        definition: "Cash generated from operations after capital expenditures. The money the business actually produces that could be returned to shareholders.",
        practical: "Arguably the most honest profitability number. GAAP earnings can be managed through accounting choices; cash either hits the bank account or it doesn't.",
      },
      {
        term: "Dividend yield",
        definition: "Annual dividends per share divided by share price.",
        practical: "A high yield (6%+) for a non-REIT stock often means the market expects the dividend to be cut — it's the market's way of pricing in a reduction before management announces it.",
      },
    ],
  },

  {
    id: "ai-terms",
    title: "App-specific terms",
    intro: "Terms that are specific to Vantage Point or worth noting because the app uses them in a particular way.",
    entries: [
      {
        term: "Setup",
        definition: "A specific configuration of price action, technicals, and news that the AI thinks is worth examining as a potential trade.",
        practical: "The AI identifies setups but does not tell you to trade them. A 'setup' is a situation worth thinking about, not a signal to act.",
      },
      {
        term: "Relevance score",
        definition: "A 0–3 score the app assigns to each news article indicating how directly it's about the ticker. 3 = primary subject; 2 = sector/peer context; 1 = tangential mention; 0 = market-wide piece that happens to mention the ticker.",
        practical: "Filter to 3 when you want the cleanest signal. Drop to 2 when you want to include sector-level pieces that matter for the company's context. The scoring is done by an AI model so expect occasional mistakes at the margins.",
      },
      {
        term: "Entry precision",
        definition: "A journal field marking whether a position was entered with known price and date ('exact'), approximately reconstructed ('approximate'), or backfilled from cost basis estimates ('backfilled').",
        practical: "The AI reads this field when discussing your positions. An 'approximate' entry gets different treatment than an 'exact' one — the AI knows the date and price may not be authoritative.",
      },
      {
        term: "Briefing",
        definition: "An AI-generated morning summary covering your watchlist, open positions, and setups worth attention. Generated on demand.",
      },
      {
        term: "Watchlist",
        definition: "Tickers you're actively tracking. Distinct from your journal, which tracks positions you actually own or have owned.",
        practical: "Adding a ticker to the watchlist triggers background fetches of price data, news, and company profile. The more you populate your watchlist, the richer your briefings become.",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Flatten for search
// ---------------------------------------------------------------------------

export function allEntries(): (GlossaryEntry & { sectionId: string; sectionTitle: string })[] {
  return SECTIONS.flatMap((s) =>
    s.entries.map((e) => ({
      ...e,
      sectionId: s.id,
      sectionTitle: s.title,
    })),
  );
}
